#
# copy this file to your source root and execute: 'docker-compose up -d bitbucket'
# inside your terminal.
#
# our bitbucket core service container using a "shadow copy" of path defined in VOLUMES
# section from another "data-only" container. this metod provide an additional protection
# for container running in production systems, prevent data-loss if deleted main core
# container accidentally.
#
bitbucket:
  restart: 'always'
  # image: dunkelfrosch/bitbucket
  build: .
  container_name: df-atls-bitbucket

  ports:
    - "7990:7990"
    - "7999:7999"

  volumes_from:
    - bitbucket_data:rw

  privileged: false
  stdin_open: true
  tty: true

#
# our bitbucket data-only container
#
bitbucket_data:
  restart: 'no'
  # image: dunkelfrosch/bitbucket
  build: .

  privileged: false
  stdin_open: false
  tty: false

  entrypoint: /bin/echo "data-only container for bitbucket"