sudo: required

env:
  COMPOSE_VERSION: 1.5.2

services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  # check normal docker build
  - docker build -t df/bitbucket:4.1.0 .
  - docker run --name df_bitbucket -d -p 127.0.0.1:7990:7990 df/bitbucket:4.1.0
  - docker ps | grep "df_bitbucket"
  - docker logs df_bitbucket
  - docker ps -aq | xargs docker rm -f
